# Generated by Django 4.2.7 on 2024-01-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
